{"uuid": "3f603934-0ea5-407c-b239-91def130d38a", "children": ["dbfdcc0e-b0a3-483a-872a-25002f2e2fbf"], "befores": [{"name": "setup_logging", "status": "broken", "statusDetails": {"message": "TypeError: Formatter.__init__() got an unexpected keyword argument 'datafmt'. Did you mean 'datefmt'?\n", "trace": "  File \"C:\\Users\\xinhang3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\xinhang3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\xinhang3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\xinhang3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\xinhang3\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\workspace\\pytest\\conftest.py\", line 32, in setup_logging\n    LogUtil.setup_logging(log_file_name)\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"D:\\workspace\\pytest\\common\\log_util.py\", line 28, in setup_logging\n    log_format = logging.Formatter(\"%(asctime)s - %(name)s - %(levelname)s - %(message)s\",datafmt=\"%Y-%m-%d %H:%M:%S\")\n"}, "start": 1738823320782, "stop": 1738823320783}], "start": 1738823320782, "stop": 1738823320991}